### ISSUE TITLE
Cannot save credential settings

### ISSUE THREAD

**Issue by yanismydj** [algolia/algoliasearch-wordpress#33]
Hey there guys,

I've been trying to get this working locally, but I've been having some issues.  When I try to save the credentials for Algolia, it POSTs just fine, and the fields are populated when the POST request appears to have gone through correctly and 302'd the client back to the same config page.  When I refresh this page, the values are all blank.

Any ideas what could be causing this or any potential solutions?

Having this issue on both Development and Staging

tested on PHP versions 5.5.18 and 5.6.2

**Comment by maxiloc** [comment]
Hi,

Can you check you have curl and php5-curl installed on your servers ?

**Comment by yanismydj** [comment]
thanks @maxiloc! 

curl & php5-curl are installed and enabled locally (development)
![screenshot 2015-06-23 15 22 08](https://cloud.githubusercontent.com/assets/575015/8318676/c02b5828-19bb-11e5-8682-eb7b4aa064e5.png)

On the Digital Ocean box (staging) php5-curl was not install, but after installing it and restarting servers, I'm still having the same issue.

I should also add that the Wordpress version I'm using is 4.2.2(latest)

**Comment by maxiloc** [comment]
@yanismydj Have you check apache/php logs ?. There might be an error somewhere.

**Comment by yanismydj** [comment]
Nothing in the `php_error.log` or `apache_error.log` (using MAMP) after this error.  For sanity: If I just enter the applicationID field and not the secret and api key fields, I can get it to throw a `PHP Fatal error:  Uncaught exception 'Exception' with message 'AlgoliaSearch requires an apiKey.'` error in the `php_error.log`.

**Comment by maxiloc** [comment]
Would you mind coming on the https://algolia.com live chat by clicking on the need help button, it will be easier to discuss ?

**Comment by yanismydj** [comment]
Support request sent!

On Tue, Jun 23, 2015 at 4:10 PM, maxiloc <notifications@github.com> wrote:

> Would you mind coming on the https://algolia.com live chat by clicking on
> the need help button, it will be easier to discuss ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/algolia/algoliasearch-wordpress/issues/33#issuecomment-114668677>
> .
>



-- 

*Yan Lhert*
Web Developer
Cell: (310) 490 4021
portfolio <http://yanismydj.github.io/YansResume/> - beatport
<http://www.beatport.com/artist/yan-lhert/103718> - mixcloud
<http://www.mixcloud.com/yanlhert/> - facebook
<https://www.facebook.com/yanismydj> - twitter
<https://twitter.com/yanismydj> - soundcloud
<https://soundcloud.com/yanismydj>

**Comment by maxiloc** [comment]
The issue has been fixed by manually creating the option row. Lets try to investigate any plugin conflict.

Here is the list of plugin:

amazon s3 and cloudfront, amazon web services, featured images in RSS, google xml sitemaps, json api, ns featured posts, wordpress SEO, wp sendgrid

**Comment by yanismydj** [comment]
quick update here: I'm still not sure what's going on here, but I've deactivated every plugin that is not Algolia and I'm still having the same problem.  I'm going to play around with the theme and see if there's something there, but no conclusion yet.

**Comment by yanismydj** [comment]
I deactivated all custom plugins and themes from the app, and moved them into a backups folder outside the app.  this bug is still occuring.  the next thing I'll try is to use 'fresh' database and see if theres something wrong with the codebase or the database.

**Comment by yanismydj** [comment]
@maxiloc After a huge amount of debugging, I figured it out! In the end, it had nothing to do with the algoliasearch-wordpress plugin and everything to do with bad configuration on my part.

The problem was that during the migration of data from my production environment to my staging and development environments, the Auto Increment field did not get migrated correctly for the `wp_options` table.  Thus, when the algoliasearch gem would try to save a row, it would fail and the options would not save.

Something is catching the exception and swallowing it, which made this hard to debug.  Other than that, this one can be chalked up to a bad migration!

Thanks again for your help @maxiloc

**Comment by maxiloc** [comment]
@yanismydj. Thanks for taking the time to debug it. Much appreciated :+1:
