### ISSUE TITLE
& still gets rendered &amp;

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-wordpress#656]
https://discourse.algolia.com/t/indexing-symbols-not-amp/2437/3

**Comment by Mamaduka** [comment]
I think this was fixed with #634, but there's no reference of this issue in PR.

**Comment by rayrutjes** [comment]
That is what I thought @Mamaduka but apparently in some cases it still happens :/

**Comment by topraf** [comment]
Hey I can confirm this still happens even with the latest version

**Comment by rayrutjes** [comment]
Hey @topraf , thanks for jumping in.
Do you have a live example?
Also  could you provide me with the raw content you have for that article that gets wrongly outputted?

**Comment by topraf** [comment]
Yes of course @rayrutjes , as always it's on https://www.cadeaux-pourris.com/ ;)
Try typing "Tech" - it's the product categories that gets written "Tech &amp; Gadgets"

**Comment by rayrutjes** [comment]
Ahh it is only happening on taxonomies @topraf ? That might be the issue.

**Comment by topraf** [comment]
I don't have any product with an "&" character but so far it's only in the taxonomies yes!

**Comment by rayrutjes** [comment]
Alright, let me take a look then, this is very useful thank you.

**Comment by rayrutjes** [comment]
I've managed to re-produce this on taxonomies (tags and categories) 🎉 :
![image](https://user-images.githubusercontent.com/5570853/31539268-6668f63e-b008-11e7-953c-323ae76a97c6.png)

**Comment by rayrutjes** [comment]
@topraf you can upgrade to 2.8.1 🎉 
Should be fixed now!

All you need to do is hit the `re-index` button of the impacted indices.

**Comment by topraf** [comment]
That was quick; thanks!

**Comment by rayrutjes** [comment]
Well actually it took way too long, but the fact that you jumped in made it super simple to tackle.
Thanks again @topraf ❤️

**Comment by rayrutjes** [comment]
Arf, we still have the issue for terms inside of posts and searchable posts records:
![image](https://user-images.githubusercontent.com/5570853/31542587-deba329c-b012-11e7-8c41-c9c7847d34d9.png)

**Comment by OriginalUserName** [comment]
Is this problem back ? I'm seeing & rendered as `&amp;` in the autocomplete dropdown : 

https://imgur.com/a/mMRDxny
